// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqtddxrveiopvhgdtvpr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxdGRkeHJ2ZWlvcHZoZ2R0dnByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyNDEwOTAsImV4cCI6MjA1NTgxNzA5MH0.Gyk0FZnnqHUWYsTfDmcZIiUdEM2WbysmqbcWCiU4pKQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);